add get_default_release.py to figure out the archive used by the currentl yrunning system
Using /etc/os-release will return testing even when using unstable.

diff --git a/debian/tests/unshare b/debian/tests/unshare
--- a/debian/tests/unshare
+++ b/debian/tests/unshare
@@ -13,8 +13,11 @@ if [ -z ${AUTOPKGTEST_TMP+x} ]; then
 	exit 1
 fi
 
-. /etc/os-release
-release=${VERSION_CODENAME:-unstable}
+release=$(./debian/tests/get_default_release.py)
+if [ -z "$release" ]; then
+	echo "cannot get default release" >&2
+	exit 1
+fi
 nativearch=$(dpkg --print-architecture)
 
 mkdir -p "${AUTOPKGTEST_TMP}/gpghome"
diff --git a/debian/tests/unshare-qemuwrapper b/debian/tests/unshare-qemuwrapper
--- a/debian/tests/unshare-qemuwrapper
+++ b/debian/tests/unshare-qemuwrapper
@@ -28,8 +28,11 @@ EXTRA_DEPS=gnupg,sbuild,mmdebstrap,build-essential,uidmap,fakeroot,diffoscope,de
 PORT=$(python3 -c 'from socket import socket; s=socket(); s.bind(("", 0)); print(s.getsockname()[1]);' || echo 10022)
 SCRIPT=./debian/tests/unshare
 
-. /etc/os-release
-release=${VERSION_CODENAME:-unstable}
+release=$(./debian/tests/get_default_release.py)
+if [ -z "$release" ]; then
+	echo "cannot get default release" >&2
+	exit 1
+fi
 
 if [ "$ID" = ubuntu ]; then
 	COMPONENTS=main,universe
